### ISSUE TITLE
Varient calling pipline

### ISSUE THREAD

**Issue by exhgphan** [epi2me-labs/wf-amplicon#16]
### Ask away!

Hi Julien, 

Ive attached a copy of the report. Again we are using the unzipped files from the fasta_pass folder, included all of our reference sequences in 1 file, and have tried lowering the min_read_qual. 

[Workflow Amplicon Sequencing report.pdf](https://github.com/epi2me-labs/wf-amplicon/files/15132882/Workflow.Amplicon.Sequencing.report.pdf)

**Comment by julibeg** [comment]
Hi there!

> from the fasta_pass folder

Sorry, do you mean the `fastq_pass` folder?

Also, according to the report it looks like there were only two reads in your data in total. Are you certain that you used the `fastq_pass` directory of a successful sequencing run? Could you share the MinKNOW reports of this run?

Thanks!

**Comment by exhgphan** [comment]
I believe we did but I'm currently at home so I only have a limited amount of files but I can send it over in an hour if that is ok. Please do not feel obligated to wait for me to respond with it.  We believe had only two reads since the nanopore was expired, we are not sure if that has anything to do with it, since some reads did come through which I have attached here. 

<img width="878" alt="Screenshot 2024-04-26 at 9 26 13 AM" src="https://github.com/epi2me-labs/wf-amplicon/assets/136051606/47806d0f-5a0e-482a-a9bb-0f58ea3cf60e">

**Comment by julibeg** [comment]
>but I can send it over in an hour if that is ok

No worries! Just send them over whenever is convenient for you

It's hard to tell from the screenshot, but the empty white space at the bottom suggests that there is indeed only a single read in that file.

**Comment by exhgphan** [comment]
Hi, would you know what the miniKNOW report would be called? And yes we took the data from the fastq_pass folder

**Comment by julibeg** [comment]
In the same directory where you found the `fastq_pass` directory, there should be several other files (e.g. `sequencing_summary_*.txt` or `report_*.{html,json,md}`). If `report_*.html` is present, please upload this one. Otherwise, the sequencing summary will also do.

Thanks!

**Comment by exhgphan** [comment]
[sequencing_summary_FAX68352_e79adb5a_9ccdd512.txt](https://github.com/epi2me-labs/wf-amplicon/files/15133852/sequencing_summary_FAX68352_e79adb5a_9ccdd512.txt)
[MinKNOW Run Report-15-04-2024-FAX68352.pdf](https://github.com/epi2me-labs/wf-amplicon/files/15133866/MinKNOW.Run.Report-15-04-2024-FAX68352.pdf)
I believe these are the files which you are looking for

**Comment by julibeg** [comment]
Hi @exhgphan, it looks like none of the reads were assigned a barcode (they are all unclassified; see screenshot below). If there is a `report_*.json` file in this directory, could you provide this as well? Thanks!

![image](https://github.com/epi2me-labs/wf-amplicon/assets/37619875/76672ad5-9945-4a52-b420-fe25d63c0b4b)

**Comment by exhgphan** [comment]
Ok, so we need to also include a barcode sheet defining them when we run this workflow?

**Comment by exhgphan** [comment]
[report_FAX68352_20240415_1526_e79adb5a.json](https://github.com/epi2me-labs/wf-amplicon/files/15133916/report_FAX68352_20240415_1526_e79adb5a.json)

**Comment by julibeg** [comment]
Hi @exhgphan, many apologies for the delay!

>Ok, so we need to also include a barcode sheet defining them when we run this workflow?

When you used barcodes (e.g. for different samples) and want to analyse them separately, then you need to demultiplex them.

However, if you sequenced only one sample, you can run the workflow again while enabling the analysis of unclassified reads. On the command line, you would do this by adding the `--analyse_unclassified` flag. In the EPI2ME Desktop Application, you would tick the "Analyse unclassified reads" box in the "Input Options" panel (see screenshot).

![image](https://github.com/epi2me-labs/wf-amplicon/assets/37619875/371b4ebc-78d0-426f-8a44-2fa18046209d)

Please let me know if that helps.

**Comment by exhgphan** [comment]
Hi, 
That makes sense. Was not having a CSV file the cause of this issue?

**Comment by julibeg** [comment]
Demultiplexing should also work without a CSV. Which library preparation kit did you use?

**Comment by exhgphan** [comment]
SQK-LSK114 is the ligation kit we used and the barcode expansion kit used was EXP-PBC096

**Comment by julibeg** [comment]
Hi @exhgphan, many thanks again for providing all the files. I had another closer look and generally it appears that something went wrong with this sequencing run.

Fist of all, output (~3000 reads) is really low. Depending on the number of barcodes that were actually used, this might be too little data even with perfect demultiplexing. The reasons for the low output seem to be low pore occupancy, but also the relatively short sequencing time (three hours). Also, demultiplexing failed for almost all reads due to low barcode scores. Are you certain that EXP-PBC096 was used in the lab and not another barcoding kit (e.g. SQK-NBD114.96)?

Generally, my best guess would be that something went wrong during the library prep. Therefore, I'd recommend reaching out to the ONT customer support (either via the webpage or by sending an email to support@nanoporetech.com) to see if they can help resolve the issue.

If you also want to try more options on the analysis side, I guess there are two things you could do:
* try demultiplexing with [Dorado](https://github.com/nanoporetech/dorado) and see if you get fewer unclassified reads this way
* run the workflow with `--analyse_unclassified` (but this only makes sense if there was just a single sample)

**Comment by exhgphan** [comment]
Hi, I think the flow cell was not great quality overall and the run time was so low since it was near the end of day. Yes we are certain of the barcoding kit was EXP-PBC096. We have new data that should be of better quality so I will try again.

**Comment by julibeg** [comment]
Closing this for now; feel free to re-open if you experience the same problem again!
